title: 담백로그
author: OGOONS
email: ogoons@hanmail.net
description: > # this means to ignore newlines until "show_exerpts:"
  No comments
show_excerpts: true # set to true to show excerpts on the homepage
permalink: /:title
url: "https://ogoons.github.com"

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: OGOONS
  tagline: 담백로그
  date_format: "%Y-%m-%d"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image: "assets/ogoons.png" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "kr" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  disqus_shortname: ogoons
  condensed_mobile:
    - home
    - page
    - post

  navigation:
      - title: About
        url: "/about"
  # generate social links in footer
  social_links:
    github: ogoons
    email: ogonns@hanmail.net
    #dribbble: jekyll
    #flickr:   jekyll
    #instagram: jekyll
    #pinterest: jekyll
    #youtube: jekyll
    #facebook: jekyll
    #soundcloud: jekyll
    #telegram: jekyll
    #gitlab: jekyll


    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
# - about.md

# Build settings
# theme: plainwhite
remote_theme: samarsault/plainwhite-jekyll

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
